(self.AMP=self.AMP||[]).push({n:"amp-facebook-like",v:"2004030010070",f:(function(AMP,_){
var aa="function"==typeof Object.create?Object.create:function(a){function c(){}c.prototype=a;return new c},p;if("function"==typeof Object.setPrototypeOf)p=Object.setPrototypeOf;else{var r;a:{var ba={a:!0},x={};try{x.__proto__=ba;r=x.a;break a}catch(a){}r=!1}p=r?function(a,c){a.__proto__=c;if(a.__proto__!==c)throw new TypeError(a+" is not extensible");return a}:null}var z=p;function A(a,c){c=void 0===c?"":c;try{return decodeURIComponent(a)}catch(b){return c}};var ca=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function B(a){var c=Object.create(null);if(!a)return c;for(var b;b=ca.exec(a);){var d=A(b[1],b[1]),e=b[2]?A(b[2].replace(/\+/g," "),b[2]):"";c[d]=e}return c};var C="";
function D(){var a=void 0,c=a||self;if(c.__AMP_MODE)var b=c.__AMP_MODE;else{b=c;var d=self.AMP_CONFIG||{},e=!!d.test||!1,f=B(b.location.originalHash||b.location.hash);d=d.spt;var g=B(b.location.search);C||(C=b.AMP_CONFIG&&b.AMP_CONFIG.v?b.AMP_CONFIG.v:"012004030010070");b={localDev:!1,development:!!(0<=["1","actions","amp","amp4ads","amp4email"].indexOf(f.development)||b.AMP_DEV_MODE),examiner:"2"==f.development,esm:!1,geoOverride:f["amp-geo"],minified:!0,lite:void 0!=g.amp_lite,test:e,log:f.log,version:"2004030010070",
rtvVersion:C,singlePassType:d};b=c.__AMP_MODE=b}return b};var da=Object.prototype.toString;var E=self.AMP_CONFIG||{},F={thirdParty:E.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:E.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof E.thirdPartyFrameRegex?new RegExp(E.thirdPartyFrameRegex):E.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:E.cdnUrl||"https://cdn.ampproject.org",cdnProxyRegex:("string"==typeof E.cdnProxyRegex?new RegExp(E.cdnProxyRegex):E.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,
errorReporting:E.errorReportingUrl||"https://amp-error-reporting.appspot.com/r",localDev:E.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:E.geoApiUrl};self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var G=self.__AMP_LOG;function H(){if(!G.user)throw Error("failed to call initLogConstructor");return G.user}function I(){if(G.dev)return G.dev;throw Error("failed to call initLogConstructor");}function J(a,c,b,d,e){H().assert(a,c,b,d,e,void 0,void 0,void 0,void 0,void 0,void 0)};function K(a){return a||{}};function L(){var a=100;this.w=a;this.l=this.m=0;this.j=Object.create(null)}L.prototype.has=function(a){return!!this.j[a]};L.prototype.get=function(a){var c=this.j[a];if(c)return c.access=++this.l,c.payload};L.prototype.put=function(a,c){this.has(a)||this.m++;this.j[a]={payload:c,access:this.l};if(!(this.m<=this.w)){I().warn("lru-cache","Trimming LRU cache");a=this.j;var b=this.l+1,d;for(d in a){var e=a[d].access;if(e<b){b=e;var f=d}}void 0!==f&&(delete a[f],this.m--)}};function M(a,c){return c.length>a.length?!1:0==a.lastIndexOf(c,0)};K({c:!0,v:!0,a:!0,ad:!0,action:!0});var N,O;
function P(a){var c;N||(N=self.document.createElement("a"),O=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new L));var b=c?null:O,d=N;if(b&&b.has(a))a=b.get(a);else{d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;
e.origin=d.origin&&"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;b&&b.put(a,e);a=e}return a};function ea(a){var c="";try{"localStorage"in a&&(c=a.localStorage.getItem("amp-experiment-toggles"))}catch(e){I().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var b=c?c.split(/\s*,\s*/g):[];a=Object.create(null);for(var d=0;d<b.length;d++)0!=b[d].length&&("-"==b[d][0]?a[b[d].substr(1)]=!1:a[b[d]]=!0);return a};function Q(a,c){a=a.__AMP_TOP||(a.__AMP_TOP=a);return R(a,c)}function fa(a,c){var b=S(a);b=S(b);b=b.isSingleDoc()?b.win:b;return R(b,c)}function S(a){return a.nodeType?Q((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function R(a,c){var b=a.__AMP_SERVICES;b||(b=a.__AMP_SERVICES={});var d=b;a=d[c];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var T;function ha(a,c){var b=void 0,d=a,e=c;var f=function(a){try{return e(a)}catch(t){throw self.__AMP_REPORT_ERROR(t),t;}};var g=ia(),h=!1;b&&(h=b.capture);d.addEventListener("message",f,g?b:h);return function(){d&&d.removeEventListener("message",f,g?b:h);f=d=e=null}}function ia(){if(void 0!==T)return T;T=!1;try{var a={get capture(){T=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(c){}return T};function ja(a,c){return ha(a,c)};function ka(a){for(var c=a.nodeName,b=0,d=0,e=a.previousElementSibling;e&&25>d&&100>b;)e.nodeName==c&&d++,b++,e=e.previousElementSibling;return 25>d&&100>b?"."+d:""};var U,la="Webkit webkit Moz moz ms O o".split(" ");function ma(a){var c;var b=a.style;if(M("border","--"))b="border";else{U||(U=Object.create(null));var d=U.border;if(!d){d="border";if(void 0===b.border){var e;b:{for(e=0;e<la.length;e++){var f=la[e]+"Border";if(void 0!==b[f]){e=f;break b}}e=""}void 0!==b[e]&&(d=e)}U.border=d}b=d}if(b){var g=c?"none"+c:"none";M(b,"--")?a.style.setProperty(b,g):a.style[b]=g}};function na(a){a=parseFloat(a);return"number"===typeof a&&isFinite(a)?a:void 0};function V(a,c){try{return JSON.parse(a)}catch(b){return c&&c(b),null}};var W={};
function oa(a,c){J("facebook","Attribute type required for <amp-ad>: %s",c);var b=0;for(var d=a;d&&d!=d.parent;d=d.parent)b++;b=String(b)+"-"+pa(a);var e=d={},f=c.dataset,g;for(g in f)M(g,"vars")||(e[g]=f[g]);if(g=c.getAttribute("json")){g=V(g);if(void 0===g)throw H().createError("Error parsing JSON in json attribute in element %s",c);for(var h in g)e[h]=g[h]}h=d;d=Date.now();e=c.getAttribute("width");g=c.getAttribute("height");h=h?h:{};h.width=na(e);h.height=na(g);c.getAttribute("title")&&(h.title=
c.getAttribute("title"));var m=a.location.href;"about:srcdoc"==m&&(m=a.parent.location.href);var t=S(c),l=fa(c,"documentInfo").get();e=fa(c,"viewer").getUnconfirmedReferrerUrl();var v=c.getPageLayoutBox();g=h;f=F.thirdParty+"/2004030010070/ampcontext-v0.js";var y=l.sourceUrl,ua=l.canonicalUrl;l=l.pageViewId;m={href:m};var va=c.tagName,wa={localDev:!1,development:D().development,esm:!1,filter:D().filter,minified:!0,lite:D().lite,test:!1,log:D().log,version:D().version,rtvVersion:D().rtvVersion,singlePassType:D().singlePassType},
xa=!(!a.AMP_CONFIG||!a.AMP_CONFIG.canary);t=!t.isVisible();v=v?{left:v.left,top:v.top,width:v.width,height:v.height}:null;var ya=c.getIntersectionChangeEntry();var q=c;for(var u=[],k=0;q&&1==q.nodeType&&25>k;){var n="";q.id&&(n="/"+q.id);var za=q.nodeName.toLowerCase();u.push(""+za+n+ka(q));k++;q=q.parentElement}q=u.join();u=q.length;k=5381;for(n=0;n<u;n++)k=33*k^q.charCodeAt(n);q=String(k>>>0);if(a.__AMP__EXPERIMENT_TOGGLES)a=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);
u=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var w in a.AMP_CONFIG)k=a.AMP_CONFIG[w],"number"===typeof k&&0<=k&&1>=k&&(u[w]=Math.random()<k);if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(w=a.AMP_CONFIG["allow-doc-opt-in"],k=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]')))for(k=k.getAttribute("content").split(","),n=0;n<k.length;n++)-1!=w.indexOf(k[n])&&(u[k[n]]=!0);Object.assign(u,ea(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&
0<a.AMP_CONFIG["allow-url-opt-in"].length)for(w=a.AMP_CONFIG["allow-url-opt-in"],a=B(a.location.originalHash||a.location.hash),k=0;k<w.length;k++)n=a["e-"+w[k]],"1"==n&&(u[w[k]]=!0),"0"==n&&(u[w[k]]=!1);a=u}g._context=K({ampcontextVersion:"2004030010070",ampcontextFilepath:f,sourceUrl:y,referrer:e,canonicalUrl:ua,pageViewId:l,location:m,startTime:d,tagName:va,mode:wa,canary:xa,hidden:t,initialLayoutRect:v,initialIntersection:ya,domFingerprint:q,experimentToggles:a,sentinel:b});(c=c.getAttribute("src"))&&
(h.src=c);d=h;d.type="facebook";Object.assign(d._context,void 0);return d}
function qa(a,c){var b={},d=b.disallowCustom,e=b.allowFullscreen;b=oa(a,c);var f=a.document.createElement("iframe");W[b.type]||(W[b.type]=0);W[b.type]+=1;var g=c.getAmpDoc();a=ra(a,g,d);var h=P(a).hostname;g=JSON.stringify(K({host:h,type:b.type,count:W[b.type],attributes:b}));f.src=a;f.ampLocation=P(a);f.name=g;b.width&&(f.width=b.width);b.height&&(f.height=b.height);b.title&&(f.title=b.title);e&&f.setAttribute("allowfullscreen","true");f.setAttribute("scrolling","no");ma(f);f.onload=function(){this.readyState=
"complete"};f.setAttribute("allow","sync-xhr 'none';");var m=["facebook"];m.includes("facebook")||sa(f);f.setAttribute("data-amp-3p-sentinel",b._context.sentinel);return f}
function ra(a,c,b){var d=void 0;if(b)b=null;else if(b=d,c=c.getMetaByName("amp-3p-iframe-src")){var e=void 0===e?"source":e;J(null!=c,"%s %s must be available",'meta[name="amp-3p-iframe-src"]',e);var f=c;"string"==typeof f&&(f=P(f));var g;(g="https:"==f.protocol||"localhost"==f.hostname||"127.0.0.1"==f.hostname)||(f=f.hostname,g=f.length-10,g=0<=g&&f.indexOf(".localhost",g)==g);J(g||/^(\/\/)/.test(c),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',
'meta[name="amp-3p-iframe-src"]',e,c);J(-1==c.indexOf("?"),"3p iframe url must not include query string %s in element %s.",c,c);e=P(c);J("localhost"==e.hostname&&!b||e.origin!=P(a.location.href).origin,"3p iframe url must not be on the same origin as the current document %s (%s) in element %s. See https://github.com/ampproject/amphtml/blob/master/spec/amp-iframe-origin-policy.md for details.",c,e.origin,c);b=c+"?2004030010070"}else b=null;var h=b;(b=h)||(a.__AMP_DEFAULT_BOOTSTRAP_SUBDOMAIN=a.__AMP_DEFAULT_BOOTSTRAP_SUBDOMAIN||
"d-"+pa(a),b="https://"+a.__AMP_DEFAULT_BOOTSTRAP_SUBDOMAIN+("."+F.thirdPartyFrameHost+"/2004030010070/frame.html"));return b}function pa(a){if(a.crypto&&a.crypto.getRandomValues){var c=new Uint32Array(2);a.crypto.getRandomValues(c);var b=String(c[0])+c[1]}else b=String(a.Math.random()).substr(2)+"0";return b}
function sa(a){if(a.sandbox&&a.sandbox.supports){for(var c=["allow-top-navigation-by-user-activation","allow-popups-to-escape-sandbox"],b="allow-forms allow-modals allow-pointer-lock allow-popups allow-same-origin allow-scripts".split(" "),d=0;d<c.length;d++){var e=c[d];if(!a.sandbox.supports(e)){I().info("3p-frame","Iframe doesn't support %s",e);return}}a.sandbox=c.join(" ")+" "+b.join(" ")}};function ta(a){if(!Aa(a))return null;var c=a.indexOf("{");try{return JSON.parse(a.substr(c))}catch(b){return I().error("MESSAGING","Failed to parse message: "+a,b),null}}function Aa(a){return"string"==typeof a&&0==a.indexOf("amp-")&&-1!=a.indexOf("{")};function Ba(a,c,b){var d=a.listeningFors;!d&&b&&(d=a.listeningFors=Object.create(null));a=d||null;if(!a)return a;var e=a[c];!e&&b&&(e=a[c]=[]);return e||null}function Ca(a,c){var b=!0,d=b?c.getAttribute("data-amp-3p-sentinel"):"amp";a=Ba(a,d,!0);for(d=0;d<a.length;d++){var e=a[d];if(e.frame===c){var f=e;break}}f||(f={frame:c,events:Object.create(null)},a.push(f));return f.events}
function Da(a){for(var c=K({sentinel:"unlisten"}),b=a.length-1;0<=b;b--){var d=a[b];if(!d.frame.contentWindow){a.splice(b,1);var e=d.events,f;for(f in e)e[f].splice(0,Infinity).forEach(function(a){a(c)})}}}
function Ea(a){if(!a.listeningFors){var c=function(b){if(b.data){var c=Fa(b.data);if(c&&c.sentinel){var e=b.source;var f=Ba(a,c.sentinel);if(f){for(var g,h=0;h<f.length;h++){var m=f[h],t=m.frame.contentWindow;if(t){var l;if(!(l=e==t))b:{for(l=e;l&&l!=l.parent;l=l.parent)if(l==t){l=!0;break b}l=!1}if(l){g=m;break}}else setTimeout(Da,0,f)}e=g?g.events:null}else e=f;var v=e;if(v){var y=v[c.type];if(y)for(y=y.slice(),e=0;e<y.length;e++)(0,y[e])(c,b.source,b.origin,b)}}}};a.addEventListener("message",
c)}}function Ga(a,c){function b(b,d,g,m){if("amp"==b.sentinel){if(d!=a.contentWindow)return;var l="null"==g&&f;if(h!=g&&!l)return}if(e||d==a.contentWindow)"unlisten"==b.sentinel?t():c(b,d,g,m)}var d="embed-size",e,f,g=a.ownerDocument.defaultView;Ea(g);g=Ca(g,a);var h=P(a.src).origin,m=g[d]||(g[d]=[]);m.push(b);var t=function(){if(b){var a=m.indexOf(b);-1<a&&m.splice(a,1);c=m=b=null}}}
function Fa(a){"string"==typeof a&&(a="{"==a.charAt(0)?V(a,function(a){I().warn("IFRAME-HELPER","Postmessage could not be parsed. Is it in a valid JSON format?",a)})||null:Aa(a)?ta(a):null);return a};function X(a){var c=AMP.BaseElement.call(this,a)||this;c.h=null;a=a.hasAttribute("data-locale")?a.getAttribute("data-locale"):window.navigator.language.replace("-","_");c.A=a;c.o=null;return c}var Y=AMP.BaseElement;X.prototype=aa(Y.prototype);X.prototype.constructor=X;if(z)z(X,Y);else for(var Z in Y)if("prototype"!=Z)if(Object.defineProperties){var Ha=Object.getOwnPropertyDescriptor(Y,Z);Ha&&Object.defineProperty(X,Z,Ha)}else X[Z]=Y[Z];X.C=Y.prototype;X.prototype.renderOutsideViewport=function(){return.75};
X.prototype.preconnectCallback=function(a){var c=Q(this.win,"preconnect");c.url(this.getAmpDoc(),"https://facebook.com",a);c.preload(this.getAmpDoc(),"https://connect.facebook.net/"+this.A+"/sdk.js","script");var b=this.getAmpDoc(),d=ra(this.win,b,void 0);c.preload(b,d,"document");c.preload(b,F.thirdParty+"/2004030010070/f.js","script")};X.prototype.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a||"fluid"==a||"intrinsic"==a};
X.prototype.layoutCallback=function(){var a=this,c=qa(this.win,this.element);this.applyFillContent(c);Ga(c,function(b){a.attemptChangeHeight(b.height).catch(function(){})});this.o=ja(this.win,this.B.bind(this));this.toggleLoading(!0);this.element.appendChild(c);this.h=c;return this.loadPromise(c)};X.prototype.B=function(a){if(!this.h||a.source==this.h.contentWindow){var c=a.data;if(c){var b="[object Object]"===da.call(c)?c:V(c);b&&"ready"==c.action&&this.toggleLoading(!1)}}};
X.prototype.unlayoutCallback=function(){if(this.h){var a=this.h;a.parentElement&&a.parentElement.removeChild(a);this.h=null}this.o&&this.o();return!0};(function(a){a.registerElement("amp-facebook-like",X)})(self.AMP);
})});

//# sourceMappingURL=amp-facebook-like-0.1.js.map
