(self.AMP=self.AMP||[]).push({n:"amp-facebook-comments",v:"2004030010070",f:(function(AMP,_){
var q,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},w;if("function"==typeof Object.setPrototypeOf)w=Object.setPrototypeOf;else{var x;a:{var ba={a:!0},y={};try{y.__proto__=ba;x=y.a;break a}catch(a){}x=!1}w=x?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var A=w;function B(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var ca=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function C(a){var b=Object.create(null);if(!a)return b;for(var c;c=ca.exec(a);){var d=B(c[1],c[1]),e=c[2]?B(c[2].replace(/\+/g," "),c[2]):"";b[d]=e}return b};var D="";
function E(){var a=void 0,b=a||self;if(b.__AMP_MODE)var c=b.__AMP_MODE;else{c=b;var d=self.AMP_CONFIG||{},e=!!d.test||!1,f=C(c.location.originalHash||c.location.hash);d=d.spt;var g=C(c.location.search);D||(D=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"012004030010070");c={localDev:!1,development:!!(0<=["1","actions","amp","amp4ads","amp4email"].indexOf(f.development)||c.AMP_DEV_MODE),examiner:"2"==f.development,esm:!1,geoOverride:f["amp-geo"],minified:!0,lite:void 0!=g.amp_lite,test:e,log:f.log,version:"2004030010070",
rtvVersion:D,singlePassType:d};c=b.__AMP_MODE=c}return c};var da=Object.prototype.toString;var F=self.AMP_CONFIG||{},G={thirdParty:F.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:F.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof F.thirdPartyFrameRegex?new RegExp(F.thirdPartyFrameRegex):F.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:F.cdnUrl||"https://cdn.ampproject.org",cdnProxyRegex:("string"==typeof F.cdnProxyRegex?new RegExp(F.cdnProxyRegex):F.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,
errorReporting:F.errorReportingUrl||"https://amp-error-reporting.appspot.com/r",localDev:F.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:F.geoApiUrl};self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var H=self.__AMP_LOG;function I(){if(!H.user)throw Error("failed to call initLogConstructor");return H.user}function J(){if(H.dev)return H.dev;throw Error("failed to call initLogConstructor");}function K(a,b,c,d,e){I().assert(a,b,c,d,e,void 0,void 0,void 0,void 0,void 0,void 0)};function L(a){return a||{}};function M(){var a=100;this.w=a;this.l=this.m=0;this.j=Object.create(null)}M.prototype.has=function(a){return!!this.j[a]};M.prototype.get=function(a){var b=this.j[a];if(b)return b.access=++this.l,b.payload};M.prototype.put=function(a,b){this.has(a)||this.m++;this.j[a]={payload:b,access:this.l};if(!(this.m<=this.w)){J().warn("lru-cache","Trimming LRU cache");a=this.j;var c=this.l+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.m--)}};function N(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};L({c:!0,v:!0,a:!0,ad:!0,action:!0});var O,P;
function Q(a){var b;O||(O=self.document.createElement("a"),P=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new M));var c=b?null:P,d=O;if(c&&c.has(a))a=c.get(a);else{d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;
e.origin=d.origin&&"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;c&&c.put(a,e);a=e}return a};function ea(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(e){J().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var c=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var d=0;d<c.length;d++)0!=c[d].length&&("-"==c[d][0]?a[c[d].substr(1)]=!1:a[c[d]]=!0);return a};function fa(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return ha(a,b)}function ia(a,b){var c=R(a);c=R(c);c=c.isSingleDoc()?c.win:c;return ha(c,b)}function R(a){return a.nodeType?fa((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function ha(a,b){var c=a.__AMP_SERVICES;c||(c=a.__AMP_SERVICES={});var d=c;a=d[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var S;var ja=['<svg viewBox="0 0 72 72"><path fill=currentColor d="M46,36c0-5.5-4.5-10-10-10s-10,4.5-10,10c0,5,3.7,9.1,8.4,9.9v-7h-2.5V36h2.5v-2.2c0-2.5,1.5-3.9,3.8-3.9\n                c1.1,0,2.2,0.2,2.2,0.2v2.5h-1.3c-1.2,0-1.6,0.8-1.6,1.6V36h2.8l-0.4,2.9h-2.3v7C42.3,45.1,46,41,46,36z"/><path fill=#ffffff class=i-amphtml-new-loader-transparent-on-shim d="M39.9,38.9l0.4-2.9h-2.8v-1.9c0-0.8,0.4-1.6,1.6-1.6h1.3v-2.5c0,0-1.1-0.2-2.2-0.2c-2.3,0-3.8,1.4-3.8,3.9V36\n                h-2.5v2.9h2.5v7c0.5,0.1,1,0.1,1.6,0.1s1.1,0,1.6-0.1v-7H39.9z"/></svg>'];var T;function ka(a,b){var c=void 0,d=a,e=b;var f=function(a){try{return e(a)}catch(r){throw self.__AMP_REPORT_ERROR(r),r;}};var g=la(),h=!1;c&&(h=c.capture);d.addEventListener("message",f,g?c:h);return function(){d&&d.removeEventListener("message",f,g?c:h);f=d=e=null}}function la(){if(void 0!==T)return T;T=!1;try{var a={get capture(){T=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return T};function ma(a,b){return ka(a,b)};function na(a){for(var b=a.nodeName,c=0,d=0,e=a.previousElementSibling;e&&25>d&&100>c;)e.nodeName==b&&d++,c++,e=e.previousElementSibling;return 25>d&&100>c?"."+d:""};var U,oa="Webkit webkit Moz moz ms O o".split(" ");function pa(a){var b;var c=a.style;if(N("border","--"))c="border";else{U||(U=Object.create(null));var d=U.border;if(!d){d="border";if(void 0===c.border){var e;b:{for(e=0;e<oa.length;e++){var f=oa[e]+"Border";if(void 0!==c[f]){e=f;break b}}e=""}void 0!==c[e]&&(d=e)}U.border=d}c=d}if(c){var g=b?"none"+b:"none";N(c,"--")?a.style.setProperty(c,g):a.style[c]=g}};function qa(a){a=parseFloat(a);return"number"===typeof a&&isFinite(a)?a:void 0};function V(a,b){try{return JSON.parse(a)}catch(c){return b&&b(c),null}};var W={};
function ra(a,b){K("facebook","Attribute type required for <amp-ad>: %s",b);var c=0;for(var d=a;d&&d!=d.parent;d=d.parent)c++;c=String(c)+"-"+sa(a);var e=d={},f=b.dataset,g;for(g in f)N(g,"vars")||(e[g]=f[g]);if(g=b.getAttribute("json")){g=V(g);if(void 0===g)throw I().createError("Error parsing JSON in json attribute in element %s",b);for(var h in g)e[h]=g[h]}h=d;d=Date.now();e=b.getAttribute("width");g=b.getAttribute("height");h=h?h:{};h.width=qa(e);h.height=qa(g);b.getAttribute("title")&&(h.title=
b.getAttribute("title"));var m=a.location.href;"about:srcdoc"==m&&(m=a.parent.location.href);var r=R(b),l=ia(b,"documentInfo").get();e=ia(b,"viewer").getUnconfirmedReferrerUrl();var u=b.getPageLayoutBox();g=h;f=G.thirdParty+"/2004030010070/ampcontext-v0.js";var z=l.sourceUrl,xa=l.canonicalUrl;l=l.pageViewId;m={href:m};var ya=b.tagName,za={localDev:!1,development:E().development,esm:!1,filter:E().filter,minified:!0,lite:E().lite,test:!1,log:E().log,version:E().version,rtvVersion:E().rtvVersion,singlePassType:E().singlePassType},
Aa=!(!a.AMP_CONFIG||!a.AMP_CONFIG.canary);r=!r.isVisible();u=u?{left:u.left,top:u.top,width:u.width,height:u.height}:null;var Ba=b.getIntersectionChangeEntry();var p=b;for(var t=[],k=0;p&&1==p.nodeType&&25>k;){var n="";p.id&&(n="/"+p.id);var Ca=p.nodeName.toLowerCase();t.push(""+Ca+n+na(p));k++;p=p.parentElement}p=t.join();t=p.length;k=5381;for(n=0;n<t;n++)k=33*k^p.charCodeAt(n);p=String(k>>>0);if(a.__AMP__EXPERIMENT_TOGGLES)a=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);
t=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var v in a.AMP_CONFIG)k=a.AMP_CONFIG[v],"number"===typeof k&&0<=k&&1>=k&&(t[v]=Math.random()<k);if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(v=a.AMP_CONFIG["allow-doc-opt-in"],k=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]')))for(k=k.getAttribute("content").split(","),n=0;n<k.length;n++)-1!=v.indexOf(k[n])&&(t[k[n]]=!0);Object.assign(t,ea(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&
0<a.AMP_CONFIG["allow-url-opt-in"].length)for(v=a.AMP_CONFIG["allow-url-opt-in"],a=C(a.location.originalHash||a.location.hash),k=0;k<v.length;k++)n=a["e-"+v[k]],"1"==n&&(t[v[k]]=!0),"0"==n&&(t[v[k]]=!1);a=t}g._context=L({ampcontextVersion:"2004030010070",ampcontextFilepath:f,sourceUrl:z,referrer:e,canonicalUrl:xa,pageViewId:l,location:m,startTime:d,tagName:ya,mode:za,canary:Aa,hidden:r,initialLayoutRect:u,initialIntersection:Ba,domFingerprint:p,experimentToggles:a,sentinel:c});(b=b.getAttribute("src"))&&
(h.src=b);d=h;d.type="facebook";Object.assign(d._context,void 0);return d}
function ta(a,b){var c={},d=c.disallowCustom,e=c.allowFullscreen;c=ra(a,b);var f=a.document.createElement("iframe");W[c.type]||(W[c.type]=0);W[c.type]+=1;var g=b.getAmpDoc();a=ua(a,g,d);var h=Q(a).hostname;g=JSON.stringify(L({host:h,type:c.type,count:W[c.type],attributes:c}));f.src=a;f.ampLocation=Q(a);f.name=g;c.width&&(f.width=c.width);c.height&&(f.height=c.height);c.title&&(f.title=c.title);e&&f.setAttribute("allowfullscreen","true");f.setAttribute("scrolling","no");pa(f);f.onload=function(){this.readyState=
"complete"};f.setAttribute("allow","sync-xhr 'none';");var m=["facebook"];m.includes("facebook")||va(f);f.setAttribute("data-amp-3p-sentinel",c._context.sentinel);return f}
function ua(a,b,c){var d=void 0;if(c)c=null;else if(c=d,b=b.getMetaByName("amp-3p-iframe-src")){var e=void 0===e?"source":e;K(null!=b,"%s %s must be available",'meta[name="amp-3p-iframe-src"]',e);var f=b;"string"==typeof f&&(f=Q(f));var g;(g="https:"==f.protocol||"localhost"==f.hostname||"127.0.0.1"==f.hostname)||(f=f.hostname,g=f.length-10,g=0<=g&&f.indexOf(".localhost",g)==g);K(g||/^(\/\/)/.test(b),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',
'meta[name="amp-3p-iframe-src"]',e,b);K(-1==b.indexOf("?"),"3p iframe url must not include query string %s in element %s.",b,b);e=Q(b);K("localhost"==e.hostname&&!c||e.origin!=Q(a.location.href).origin,"3p iframe url must not be on the same origin as the current document %s (%s) in element %s. See https://github.com/ampproject/amphtml/blob/master/spec/amp-iframe-origin-policy.md for details.",b,e.origin,b);c=b+"?2004030010070"}else c=null;var h=c;(c=h)||(a.__AMP_DEFAULT_BOOTSTRAP_SUBDOMAIN=a.__AMP_DEFAULT_BOOTSTRAP_SUBDOMAIN||
"d-"+sa(a),c="https://"+a.__AMP_DEFAULT_BOOTSTRAP_SUBDOMAIN+("."+G.thirdPartyFrameHost+"/2004030010070/frame.html"));return c}function sa(a){if(a.crypto&&a.crypto.getRandomValues){var b=new Uint32Array(2);a.crypto.getRandomValues(b);var c=String(b[0])+b[1]}else c=String(a.Math.random()).substr(2)+"0";return c}
function va(a){if(a.sandbox&&a.sandbox.supports){for(var b=["allow-top-navigation-by-user-activation","allow-popups-to-escape-sandbox"],c="allow-forms allow-modals allow-pointer-lock allow-popups allow-same-origin allow-scripts".split(" "),d=0;d<b.length;d++){var e=b[d];if(!a.sandbox.supports(e)){J().info("3p-frame","Iframe doesn't support %s",e);return}}a.sandbox=b.join(" ")+" "+c.join(" ")}};function wa(a){if(!Da(a))return null;var b=a.indexOf("{");try{return JSON.parse(a.substr(b))}catch(c){return J().error("MESSAGING","Failed to parse message: "+a,c),null}}function Da(a){return"string"==typeof a&&0==a.indexOf("amp-")&&-1!=a.indexOf("{")};function Ea(a,b,c){var d=a.listeningFors;!d&&c&&(d=a.listeningFors=Object.create(null));a=d||null;if(!a)return a;var e=a[b];!e&&c&&(e=a[b]=[]);return e||null}function Fa(a,b){var c=!0,d=c?b.getAttribute("data-amp-3p-sentinel"):"amp";a=Ea(a,d,!0);for(d=0;d<a.length;d++){var e=a[d];if(e.frame===b){var f=e;break}}f||(f={frame:b,events:Object.create(null)},a.push(f));return f.events}
function Ga(a){for(var b=L({sentinel:"unlisten"}),c=a.length-1;0<=c;c--){var d=a[c];if(!d.frame.contentWindow){a.splice(c,1);var e=d.events,f;for(f in e)e[f].splice(0,Infinity).forEach(function(a){a(b)})}}}
function Ha(a){if(!a.listeningFors){var b=function(b){if(b.data){var c=Ia(b.data);if(c&&c.sentinel){var e=b.source;var f=Ea(a,c.sentinel);if(f){for(var g,h=0;h<f.length;h++){var m=f[h],r=m.frame.contentWindow;if(r){var l;if(!(l=e==r))b:{for(l=e;l&&l!=l.parent;l=l.parent)if(l==r){l=!0;break b}l=!1}if(l){g=m;break}}else setTimeout(Ga,0,f)}e=g?g.events:null}else e=f;var u=e;if(u){var z=u[c.type];if(z)for(z=z.slice(),e=0;e<z.length;e++)(0,z[e])(c,b.source,b.origin,b)}}}};a.addEventListener("message",
b)}}function Ja(a,b){function c(c,d,g,m){if("amp"==c.sentinel){if(d!=a.contentWindow)return;var l="null"==g&&f;if(h!=g&&!l)return}if(e||d==a.contentWindow)"unlisten"==c.sentinel?r():b(c,d,g,m)}var d="embed-size",e,f,g=a.ownerDocument.defaultView;Ha(g);g=Fa(g,a);var h=Q(a.src).origin,m=g[d]||(g[d]=[]);m.push(c);var r=function(){if(c){var a=m.indexOf(c);-1<a&&m.splice(a,1);b=m=c=null}}}
function Ia(a){"string"==typeof a&&(a="{"==a.charAt(0)?V(a,function(a){J().warn("IFRAME-HELPER","Postmessage could not be parsed. Is it in a valid JSON format?",a)})||null:Da(a)?wa(a):null);return a};function X(a){var b=AMP.BaseElement.call(this,a)||this;b.h=null;a=a.hasAttribute("data-locale")?a.getAttribute("data-locale"):window.navigator.language.replace("-","_");b.A=a;b.o=null;return b}var Y=AMP.BaseElement;X.prototype=aa(Y.prototype);X.prototype.constructor=X;if(A)A(X,Y);else for(var Z in Y)if("prototype"!=Z)if(Object.defineProperties){var Ka=Object.getOwnPropertyDescriptor(Y,Z);Ka&&Object.defineProperty(X,Z,Ka)}else X[Z]=Y[Z];X.C=Y.prototype;q=X.prototype;q.renderOutsideViewport=function(){return.75};
q.preconnectCallback=function(a){var b=fa(this.win,"preconnect");b.url(this.getAmpDoc(),"https://facebook.com",a);b.preload(this.getAmpDoc(),"https://connect.facebook.net/"+this.A+"/sdk.js","script");var c=this.getAmpDoc(),d=ua(this.win,c,void 0);b.preload(c,d,"document");b.preload(c,G.thirdParty+"/2004030010070/f.js","script")};q.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a||"fluid"==a||"intrinsic"==a};
q.layoutCallback=function(){var a=this,b=ta(this.win,this.element);this.applyFillContent(b);Ja(b,function(b){a.forceChangeHeight(b.height)});this.o=ma(this.win,this.B.bind(this));this.toggleLoading(!0);this.element.appendChild(b);this.h=b;return this.loadPromise(b)};q.B=function(a){if(!this.h||a.source==this.h.contentWindow){var b=a.data;if(b){var c="[object Object]"===da.call(b)?b:V(b);c&&"ready"==b.action&&this.toggleLoading(!1)}}};
q.createLoaderLogoCallback=function(){var a=this.element;a=a.ownerDocument||a;S&&S.ownerDocument===a||(S=a.createElement("div"));a=S;a.innerHTML=ja[0];var b=a.firstElementChild;a.removeChild(b);return{color:"#1877F2",content:b}};q.unlayoutCallback=function(){if(this.h){var a=this.h;a.parentElement&&a.parentElement.removeChild(a);this.h=null}this.o&&this.o();return!0};(function(a){a.registerElement("amp-facebook-comments",X)})(self.AMP);
})});

//# sourceMappingURL=amp-facebook-comments-0.1.js.map
