(self.AMP=self.AMP||[]).push({n:"amp-accordion",v:"2004030010070",f:(function(AMP,_){
var aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},l;if("function"==typeof Object.setPrototypeOf)l=Object.setPrototypeOf;else{var m;a:{var ba={a:!0},n={};try{n.__proto__=ba;m=n.a;break a}catch(a){}m=!1}l=m?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var p=l;function q(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var ca=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var r=self.__AMP_LOG;function t(){if(!r.user)throw Error("failed to call initLogConstructor");return r.user}function u(){if(r.dev)return r.dev;throw Error("failed to call initLogConstructor");}function v(a,b,c){t().assert(a,b,c,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function da(){var a,b;this.promise=new Promise(function(c,e){a=c;b=e});this.resolve=a;this.reject=b};var w=Object.prototype.hasOwnProperty;function x(a){return 2>a.length?!1:0==a.lastIndexOf("--",0)};function y(a,b){if(a.__AMP__EXPERIMENT_TOGGLES)var c=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);c=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var e in a.AMP_CONFIG){var d=a.AMP_CONFIG[e];"number"===typeof d&&0<=d&&1>=d&&(c[e]=Math.random()<d)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(e=a.AMP_CONFIG["allow-doc-opt-in"],d=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){d=
d.getAttribute("content").split(",");for(var f=0;f<d.length;f++)-1!=e.indexOf(d[f])&&(c[d[f]]=!0)}Object.assign(c,ea(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length){e=a.AMP_CONFIG["allow-url-opt-in"];d=a.location.originalHash||a.location.hash;a=Object.create(null);if(d)for(var g;g=ca.exec(d);)f=q(g[1],g[1]),g=g[2]?q(g[2].replace(/\+/g," "),g[2]):"",a[f]=g;for(d=0;d<e.length;d++)f=a["e-"+e[d]],"1"==f&&(c[e[d]]=!0),"0"==f&&(c[e[d]]=!1)}}var h=
c;return!!h[b]}function ea(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(d){u().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var c=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var e=0;e<c.length;e++)0!=c[e].length&&("-"==c[e][0]?a[c[e].substr(1)]=!1:a[c[e]]=!0);return a};var z={},A=(z["ampdoc-fie"]={isTrafficEligible:function(){return!0},branches:[["21065001"],["21065002"]]},z);function fa(a){var b=a.ownerDocument.defaultView,c=b.__AMP_TOP||(b.__AMP_TOP=b),e=b!=c;var d=c;if(y(d,"ampdoc-fie")){d.__AMP_EXPERIMENT_BRANCHES=d.__AMP_EXPERIMENT_BRANCHES||{};for(var f in A)if(w.call(A,f)&&!w.call(d.__AMP_EXPERIMENT_BRANCHES,f))if(A[f].isTrafficEligible&&A[f].isTrafficEligible(d)){if(!d.__AMP_EXPERIMENT_BRANCHES[f]&&y(d,f)){var g=A[f].branches;d.__AMP_EXPERIMENT_BRANCHES[f]=g[Math.floor(Math.random()*g.length)]||null}}else d.__AMP_EXPERIMENT_BRANCHES[f]=null;d="21065002"===(d.__AMP_EXPERIMENT_BRANCHES?
d.__AMP_EXPERIMENT_BRANCHES["ampdoc-fie"]:null)}else d=!1;var h=d;e&&!h?a=B(b,"action")?C(b,"action"):null:(a=D(a),a=D(a),a=a.isSingleDoc()?a.win:a,a=B(a,"action")?C(a,"action"):null);return a}function E(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return C(a,b)}function D(a){return a.nodeType?E((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}
function C(a,b){B(a,b);var c=a.__AMP_SERVICES;c||(c=a.__AMP_SERVICES={});var e=c;a=e[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function B(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function ha(a,b,c){for(;a&&a!==c;a=a.parentElement)if(b(a))return a;return null};function F(a,b,c,e){var d=new G(a,b,c,e);return d.solveYValueFromXValue.bind(d)}function G(a,b,c,e){var d=1,f=1;this.y0=this.x0=0;this.x1=a;this.y1=b;this.x2=c;this.y2=e;this.x3=d;this.y3=f}G.prototype.solveYValueFromXValue=function(a){return this.getPointY(this.solvePositionFromXValue(a))};
G.prototype.solvePositionFromXValue=function(a){var b=1E-6,c=(a-this.x0)/(this.x3-this.x0);if(0>=c)return 0;if(1<=c)return 1;for(var e=0,d=1,f=0,g=0;8>g;g++){f=this.getPointX(c);var h=(this.getPointX(c+b)-f)/b;if(Math.abs(f-a)<b)return c;if(Math.abs(h)<b)break;else f<a?e=c:d=c,c-=(f-a)/h}for(g=0;Math.abs(f-a)>b&&8>g;g++)f<a?(e=c,c=(c+d)/2):(d=c,c=(c+e)/2),f=this.getPointX(c);return c};
G.prototype.getPointX=function(a){if(0==a)return this.x0;if(1==a)return this.x3;var b=this.lerp(this.x0,this.x1,a),c=this.lerp(this.x1,this.x2,a),e=this.lerp(this.x2,this.x3,a);b=this.lerp(b,c,a);c=this.lerp(c,e,a);return this.lerp(b,c,a)};G.prototype.getPointY=function(a){if(0==a)return this.y0;if(1==a)return this.y3;var b=this.lerp(this.y0,this.y1,a),c=this.lerp(this.y1,this.y2,a),e=this.lerp(this.y2,this.y3,a);b=this.lerp(b,c,a);c=this.lerp(c,e,a);return this.lerp(b,c,a)};
G.prototype.lerp=function(a,b,c){return a+c*(b-a)};var ia=F(.25,.1,.25,1),ja=F(.42,0,1,1),ka=F(0,0,.58,1),la=F(.42,0,.58,1),ma={linear:function(a){return a},ease:ia,"ease-in":ja,"ease-out":ka,"ease-in-out":la};
function H(a){if(!a)return null;if("string"==typeof a){if(-1!=a.indexOf("cubic-bezier")){var b=a.match(/cubic-bezier\((.+)\)/);if(b&&(b=b[1].split(",").map(parseFloat),4==b.length)){for(var c=0;4>c;c++)if(isNaN(b[c]))return null;return F(b[0],b[1],b[2],b[3])}return null}return ma[a]}return a};function na(){}function I(a){var b;this.l=a;(a=b)||(a=E(self,"vsync"));this.w=a;this.D=null;this.c=[]}function oa(a,b,c){var e=pa;return(new I(a)).setCurve(e).add(0,b,1).start(c)}I.prototype.setCurve=function(a){a&&(this.D=H(a));return this};I.prototype.add=function(a,b,c,e){this.c.push({delay:a,func:b,duration:c,curve:H(e)});return this};I.prototype.start=function(a){var b=new J(this.w,this.l,this.c,this.D,a);return b};
function J(a,b,c,e,d){this.w=a;this.l=b;this.c=[];for(b=0;b<c.length;b++){var f=c[b];this.c.push({delay:f.delay,func:f.func,duration:f.duration,curve:f.curve||e,started:!1,completed:!1})}this.J=d;this.O=Date.now();this.A=!0;this.G={};c=new da;this.F=c.promise;this.N=c.resolve;this.M=c.reject;this.H=this.w.createAnimTask(this.l,{mutate:this.P.bind(this)});this.w.canAnimate(this.l)?this.H(this.G):(u().warn("Animation","cannot animate"),K(this,!1,0))}
J.prototype.then=function(a,b){return a||b?this.F.then(a,b):this.F};J.prototype.thenAlways=function(a){a=a||na;return this.then(a,a)};J.prototype.halt=function(a){K(this,!1,a||0)};function K(a,b,c){if(a.A){a.A=!1;if(0!=c){1<a.c.length&&a.c.sort(function(a,b){return a.delay+a.duration-(b.delay+b.duration)});try{if(0<c)for(c=0;c<a.c.length;c++)a.c[c].func(1,!0);else for(var e=a.c.length-1;0<=e;e--)a.c[e].func(0,!1)}catch(d){u().error("Animation","completion failed: "+d,d),b=!1}}b?a.N():a.M()}}
J.prototype.P=function(){if(this.A){for(var a=Date.now(),b=Math.min((a-this.O)/this.J,1),c=0;c<this.c.length;c++){var e=this.c[c];!e.started&&b>=e.delay&&(e.started=!0)}for(c=0;c<this.c.length;c++)if(e=this.c[c],e.started&&!e.completed)a:{var d;if(0<e.duration){var f=d=Math.min((b-e.delay)/e.duration,1);if(e.curve&&1!=f)try{f=e.curve(d)}catch(g){u().error("Animation","step curve failed: "+g,g);K(this,!1,0);break a}}else f=d=1;1==d&&(e.completed=!0);try{e.func(f,e.completed)}catch(g){u().error("Animation",
"step mutate failed: "+g,g),K(this,!1,0)}}1==b?K(this,!0,0):this.w.canAnimate(this.l)?this.H(this.G):(u().warn("Animation","cancel animation"),K(this,!1,0))}};var L,M="Webkit webkit Moz moz ms O o".split(" ");function N(a,b,c){if(x(b))return b;L||(L=Object.create(null));var e=L[b];if(!e||c){e=b;if(void 0===a[b]){var d=b.charAt(0).toUpperCase()+b.slice(1);a:{for(var f=0;f<M.length;f++){var g=M[f]+d;if(void 0!==a[g]){d=g;break a}}d=""}var h=d;void 0!==a[h]&&(e=h)}c||(L[b]=e)}return e}function O(a,b,c){var e;if(b=N(a.style,b,void 0)){var d=e?c+e:c;x(b)?a.style.setProperty(b,d):a.style[b]=d}}function P(a,b){for(var c in b)O(a,c,b[c])};function Q(a,b){return function(c,e){for(var d in b){var f=d;"display"===f&&u().error("STYLE","`display` style detected. You must use toggle instead.");O(a,f,b[d](c,e))}}}function R(a,b){return function(c){return a+(b-a)*c}}function S(a){return function(b){return a(b)+"px"}};var qa=F(.47,0,.745,.715),pa=F(.39,.575,.565,1);function ra(a){return y(a,"amp-accordion-display-locking")&&("renderSubtree"in Element.prototype||!1)}function T(a){var b=AMP.BaseElement.call(this,a)||this;b.o=[];b.B=null;b.m=null;b.C=!1;b.h=null;b.j=null;b.L=a.id?a.id:Math.floor(100*Math.random());return b}var U=AMP.BaseElement;T.prototype=aa(U.prototype);T.prototype.constructor=T;
if(p)p(T,U);else for(var V in U)if("prototype"!=V)if(Object.defineProperties){var sa=Object.getOwnPropertyDescriptor(U,V);sa&&Object.defineProperty(T,V,sa)}else T[V]=U[V];T.S=U.prototype;T.prototype.isLayoutSupported=function(a){return"container"==a};
T.prototype.buildCallback=function(){var a=this;this.j=fa(this.element);this.C=this.element.hasAttribute("disable-session-states");this.B=ta(this);this.m=ua(this);this.h=this.getRealChildren();this.h.forEach(function(b,c){v("section"==b.tagName.toLowerCase(),"Sections should be enclosed in a <section> tag, See https://github.com/ampproject/amphtml/blob/master/extensions/amp-accordion/amp-accordion.md. Found in: %s",a.element);var e=b.children;v(2==e.length,"Each section must have exactly two children. See https://github.com/ampproject/amphtml/blob/master/extensions/amp-accordion/amp-accordion.md. Found in: %s",
a.element);var d=e[1];d.classList.add("i-amphtml-accordion-content");var f=d.getAttribute("id");f||(f=a.L+"_AMP_content_"+c,d.setAttribute("id",f));a.registerAction("toggle",function(b){return W(a,b)});a.registerAction("expand",function(b){return W(a,b)});a.registerAction("collapse",function(b){return W(a,b)});var g=new a.win.MutationObserver(function(b){va(a,b)});g.observe(b,{attributes:!0,attributeFilter:["data-expand"]});a.m[f]?b.setAttribute("expanded",""):!1===a.m[f]&&b.removeAttribute("expanded");
a.mutateElement(function(){});var h=b.hasAttribute("expanded");c=e[0];c.classList.add("i-amphtml-accordion-header");c.setAttribute("role","button");c.setAttribute("aria-controls",f);c.setAttribute("aria-expanded",String(h));X(a,d,h?"":"invisible skip-viewport-activation");c.hasAttribute("tabindex")||c.setAttribute("tabindex",0);a.o.push(c);v(0==a.j.hasAction(c,"tap",b),"amp-accordion headings should not have tap actions registered.");c.addEventListener("click",a.I.bind(a));c.addEventListener("keydown",
a.K.bind(a));ra(a.win)&&d.addEventListener("rendersubtreeactivation",function(b){var c=b.target.parentElement;Y(a,c,1,!0)})})};function W(a,b){var c=b,e=c.method,d=c.args,f=c.trust,g=void 0;"expand"===e?g=!0:"collapse"===e&&(g=!1);if(d){var h=d.section,k=a.getAmpDoc().getElementById(h);k=t().assertElement(k);v(k,"No element found with id: %s",h);Y(a,k,f,g)}else for(c=0;c<a.h.length;c++)Y(a,a.h[c],f,g)}
function ta(a){var b=a.element.id||a.element.getResourceId();a=a.win.location.href;var c=a.indexOf("#");a=-1==c?a:a.substring(0,c);return"amp-"+b+"-"+a}function ua(a){if(a.C)return{};try{var b=a.win.sessionStorage.getItem(a.B);return b?JSON.parse(b):{}}catch(c){return{}}}function wa(a){if(!a.C){var b=JSON.stringify(a.m);try{a.win.sessionStorage.setItem(a.B,b)}catch(c){}}}
function Z(a,b,c,e){var d=a.win;var f="accordionSection."+b;var g={};var h={detail:g};Object.assign(h,void 0);"function"==typeof d.CustomEvent?f=new d.CustomEvent(f,h):(d=d.document.createEvent("CustomEvent"),d.initCustomEvent(f,!!h.bubbles,!!h.cancelable,g),f=d);a.j.trigger(c,b,f,e);a.element.dispatchCustomEvent(b)}
function Y(a,b,c,e){var d=b.children,f=d[0],g=d[1];d=g.getAttribute("id");var h=b.hasAttribute("expanded"),k=void 0==e?!b.hasAttribute("expanded"):e;k&&b.hasAttribute("expanded")||!k&&!b.hasAttribute("expanded")||(a.element.hasAttribute("animate")?k?(f.setAttribute("aria-expanded","true"),X(a,g,""),xa(a,b,c),a.element.hasAttribute("expand-single-section")&&a.h.forEach(function(d){d!=b&&(ya(a,d,c),d.children[0].setAttribute("aria-expanded","false"),X(a,d.children[1],"invisible skip-viewport-activation"))})):
(f.setAttribute("aria-expanded","false"),X(a,g,"invisible skip-viewport-activation"),ya(a,b,c)):a.mutateElement(function(){k?(Z(a,"expand",b,c),b.setAttribute("expanded",""),X(a,g,""),f.setAttribute("aria-expanded","true"),a.element.hasAttribute("expand-single-section")&&a.h.forEach(function(d){d!=b&&(d.hasAttribute("expanded")&&(Z(a,"collapse",d,c),d.removeAttribute("expanded")),d.children[0].setAttribute("aria-expanded","false"),X(a,d.children[1],"invisible skip-viewport-activation"))})):(Z(a,"collapse",
b,c),b.removeAttribute("expanded"),f.setAttribute("aria-expanded","false"),X(a,g,"invisible skip-viewport-activation"))},b),a.m[d]=!h,wa(a))}function X(a,b,c){ra(a.win)&&b&&(b.renderSubtree=c)}
function xa(a,b,c){var e,d,f,g,h,k=b.children[1];a.measureMutateElement(function(){e=b.offsetWidth;var a=k,c=N(a.style,"width",void 0);h=c?x(c)?a.style.getPropertyValue(c):a.style[c]:void 0},function(){var d={position:"fixed",width:e+"px",opacity:"0"},f=k.style,g;for(g in d)f.setProperty(N(f,g),d[g].toString(),"important");b.hasAttribute("expanded")||(Z(a,"expand",b,c),b.setAttribute("expanded",""))}).then(function(){return a.measureMutateElement(function(){d=b.offsetHeight;f=k.offsetHeight;var c=
a.getViewport().getHeight();g=za(Math.abs(f),c)},function(){P(b,{overflow:"hidden",height:d+"px"});P(k,{position:"",opacity:"",width:h})})}).then(function(){var c=new I(a.element);c.setCurve(qa);c.add(0,Q(b,{height:S(R(d,d+f))}),1);c.add(0,Q(k,{opacity:R(0,1)}),1);return c.start(g).thenAlways(function(){a.mutateElement(function(){P(b,{overflow:"",height:""});P(k,{opacity:""})})})})}
function ya(a,b,c){var e,d,f,g=b.firstElementChild;a.measureMutateElement(function(){e=b.offsetHeight;d=g.offsetHeight;var c=a.getViewport().getSize().height;f=za(Math.abs(e),c)},function(){P(b,{overflow:"hidden"})}).then(function(){return oa(b,Q(b,{height:S(R(e,d))}),f).thenAlways(function(){return a.mutateElement(function(){b.hasAttribute("expanded")&&(Z(a,"collapse",b,c),b.removeAttribute("expanded"));P(b,{height:"",overflow:""})})})})}
function za(a,b){var c=void 0===c?200:c;var e=void 0===e?500:e;var d=Math.abs(a)/b*e;return Math.min(Math.max(d,c),e)}T.prototype.I=function(a){Aa(this,a)&&(a.preventDefault(),Y(this,a.currentTarget.parentElement,3))};function Aa(a,b){var c=b.target;b=b.currentTarget;var e=!!ha(c,function(a){return"A"==a.tagName},b),d=a.j.hasAction(c,"tap",b);return!e&&!d}
T.prototype.K=function(a){if(!a.defaultPrevented)switch(a.key){case "ArrowUp":case "ArrowDown":var b=this.o.indexOf(a.currentTarget);if(-1!==b){a.preventDefault();a=(b+("ArrowUp"==a.key?-1:1))%this.o.length;0>a&&(a+=this.o.length);try{this.o[a].focus()}catch(c){}}break;case "Enter":case " ":a.target==a.currentTarget&&(a.preventDefault(),Y(this,a.currentTarget.parentElement,3))}};
function va(a,b){b.forEach(function(b){var c=b.target,d=c.hasAttribute("data-expand");c.hasAttribute("expanded")!==d&&Y(a,c,2,d)})}T.prototype.R=function(){return this.j};(function(a){a.registerElement("amp-accordion",T,".i-amphtml-accordion-content,.i-amphtml-accordion-header{margin:0}.i-amphtml-accordion-header{cursor:pointer;background-color:#efefef;padding-right:20px;border:1px solid #dfdfdf}amp-accordion>section:not([expanded])>:last-child[rendersubtree]{border:none!important;display:block!important;height:0px!important;margin:0px!important;opacity:0!important;padding:0!important;position:absolute!important;top:-999999px!important;width:100%!important}amp-accordion>section:not([expanded]) .i-amphtml-media-component,amp-accordion>section:not([expanded]) .i-amphtml-media-component *{display:none!important;visibility:hidden!important}\n/*# sourceURL=/extensions/amp-accordion/0.1/amp-accordion.css*/")})(self.AMP);
})});

//# sourceMappingURL=amp-accordion-0.1.js.map
